[package]
name = "kcashFA"
version = "1.0.0"
authors = []

[addresses]
kcash_addr = "_"

[dependencies.AptosFramework]
local = "/home/imentus/Documents/kcash_v2_contract_move_aptos"
rev = "mainnet"
subdir = "/aptos-framework"
